### ISSUE TITLE
How do you fine-tune CLIP?

### ISSUE THREAD

**Issue by jingzhengli** [zqypku/mm_poison#1]
It seems that you don't introduce how do you fine-tune CLIP with poisoned data.

**Comment by zqypku** [comment]
We finetune CLIP using the following command mentioned in the readme file:
`python -m torch.distributed.launch --nproc_per_node=1 --master_port PORT --use_env retrieval_by_CLIP.py --distributed --config CONFIG --poisoned --overload_config --output_dir OUTPUT_DIR --poisoned_file POISONED_FILE --target_txt_cls TXT_LABEL --target_img_cls IMG_LABEL --poisoned_goal POISONED_GOAL`
