### ISSUE TITLE
MIssing file `/data/pascal_train.json`

### ISSUE THREAD

**Issue by weimin17** [zqypku/mm_poison#2]
Dear authors, is there any way that I can find the file `/data/pascal_train.json`. In order to preproduce the code, this file is necessary for constructing poisoned dataset. Thanks

**Comment by zqypku** [comment]
Hi, to make it easier for you to reproduce the code, I uploaded the dataset split to Google Drive: https://drive.google.com/drive/folders/1tUEv-Q0-nLs6WpRttC_f4vvPLO9zliiY?usp=drive_link
I also add this link to the readme file.
